# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 461db46385ee1bc2a766d542c5732e3e5f676fe51fcbb9deebe6256374fb9e0fa03cdabd3a65d1553c766260cd03ca4ad0c953266a685a80267168a07183a98c

test:
  secret_key_base: 327628dee81f08d2f67b762c65b45d6ddc253c17bc9aa120c963426f69a4544f592297325a46e279bd27d71a7a0992ceb2a3c442235f324fb1c1a731eea72634

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
